pyrogram/pyrogram

- compiler/error/source/400_BAD_REQUEST.tsv
- pyrogram/client/client.py
when a phone number is banned by Telegram, Client permanently sends requests because it's an UnknownError and 'def authorize(self)' has the code without 'break' or 'raise':
```            
except Exception as e:
log.error(e, exc_info=True)
```
> Error [400 PHONE_NUMBER_BANNED]

- compiler/error/source/400_BAD_REQUEST.tsv
hi there!
add another error that was `UnknownError`. Telegram has 70 characters limitation for user's Bio field, i believe. when you try to use `functions.account.UpdateProfile()` method and pass `about` parameter more than 70 characters, then you get the error::
```
pyrogram.api.errors.error.UnknownError: [520 Unknown error]: {
"_": "types.RpcError",
"error_code": 400,
"error_message": "ABOUT_TOO_LONG"
}
```
> Error [400 ABOUT_TOO_LONG]

- pyrogram/client/client.py
Added support thumbnail preview in video.
As we can see from official desktop Telegram thumbnails have [size restrictions](https://github.com/telegramdesktop/tdesktop/blob/55e56a6788870e6d67d9938eaabdf87f2ebddb17/Telegram/SourceFiles/storage/localimageloader.cpp#L519) (maximum 90x90 pixels).
> Added sending thumb with video.

- pyrogram/client/client.py
These changes would allow **client.get_file** to write to a given file name or file like object directly
via a new **file_out** parameter.
**file_out** can be a string or file/file like object that implements at least **.write**.
The parameter is optional, and if not specified the old behavior of creating a file
in the current working directory with a generated **.temp** name is kept.
---
**client.download_media** is reworked to allow downloading files to specific locations instead
of only the downloads folder.  The function can still generate a file name for you the way it did prior if desired.
**client.download_media** would no longer make use of a temporary file, as it uses **client.get_files**
new ability to write directly to a file object.
the change in the behavior of **file_name** …
> More flexible media downloads with client.download_(media/photo) and client.get_file

- pyrogram/client/client.py
I noticed a double call to Client.stop() when quickly mashing CTRL-C on the console with the client running.
This is because the signal handler can be called again while Client.stop() is in the middle of executing.
Calling Client.stop() twice causes an exception inside the signal handler if **self.is_started** has been set to **False** already.
The exception can't be handled and it prints to the console.
I think this might be a better way to stop the idle loop, it keeps Client.stop() from being called twice when multiple signals queue up.
> Make Client.signal_handler reentrant (avoid calling Client.stop() twice)

- pyrogram/client/client.py
In reference to: https://github.com/pyrogram/pyrogram/issues/68
I see there is a TODO on this function but here is a fix.
> Make sure started Session is always stopped upon exceptions in Client.get_file

- pyrogram/client/client.py
- Added the possibility to choose a configuration file by providing its path when initializing the `Client`, instead of using the previously hard-coded "config.ini" file
- Allowing to set the `session_name` to `None` in order to make it "temporary", so that it won't be saved
> Add possibility to choose config file, implement temporary sessions

- pyrogram/client/methods/messages/send_audio.py
With the [Bot API 4.0 update](https://core.telegram.org/bots/api#july-26-2018), `sendAudio` allows bots to pass a thumbnail - making it possible for pyrogram to include a `thumb` parameter in its convenience method `send_audio`
> Allow to set audio thumbnail when using send_audio

- README.rst
- pyrogram/client/client.py
- pyrogram/client/ext/base_client.py
- pyrogram/client/ext/syncer.py
Closes #123.
Old behavior (bot token as session name) is still remaining with warning, but should be removed in future
> Add bot_token argument

- pyrogram/__init__.py
@delivrance  after trying so many ways to get through this, i finally solved the issue by replacing the typing from your source with mine.
i had to add a little tweaks to make it work.
**Nature of the issue**
After the last push on GitHub, my bot automatically updated and all of a sudden it was raising lots and lots of errors which got me confused
I had to disable all imports and the only one that was conflicting was sqlite3 modeule.
**Files Modified**
`pyrogram\vendor\typing`
`pyrogram/vendor/__init__.py`
That was the little contribution i could make so far.
if you see a more suitable title to give to this don't hesitate
> A global fix for Python < v3.5.6 which was causing error with sqlite3

- .gitignore
- pyrogram/client/ext/dispatcher.py
- pyrogram/client/handlers/__init__.py
- pyrogram/client/handlers/poll_handler.py
- pyrogram/client/methods/decorators/__init__.py
- pyrogram/client/methods/decorators/on_poll.py
- pyrogram/client/methods/messages/__init__.py
- pyrogram/client/methods/messages/retract_vote.py
- pyrogram/client/methods/messages/send_animation.py
- pyrogram/client/methods/messages/send_audio.py
- pyrogram/client/methods/messages/send_document.py
- pyrogram/client/methods/messages/send_poll.py
- pyrogram/client/methods/messages/send_video.py
- pyrogram/client/methods/messages/send_video_note.py
- pyrogram/client/methods/messages/stop_poll.py
- pyrogram/client/methods/messages/vote_poll.py
- pyrogram/client/types/input_media/input_media_animation.py
- pyrogram/client/types/input_media/input_media_audio.py
- pyrogram/client/types/input_media/input_media_document.py
- pyrogram/client/types/input_media/input_media_video.py
- pyrogram/client/types/messages_and_media/message.py
- pyrogram/client/types/messages_and_media/poll.py
- pyrogram/client/types/messages_and_media/poll_option.py
- pyrogram/client/types/pyrogram_type.py
- pyrogram/client/types/user_and_chats/chat.py
- pyrogram/client/types/user_and_chats/chat_member.py
The Bot API 4.2 features were already existing in Pyrogram, this PR is meant to rename some attributes and clean up some other methods' parameters to reflect the official docs.
I still need to make the new *is_member* attribute of the ChatMember type work correctly, though.
> Bot API 4.2

- pyrogram/client/ext/dispatcher.py
Previously, when handler.check raised errors, it would be excepted by the try on line 153, and would fail to loop through the rest of the groups/handlers.
> Try/except handler.check()

- pyrogram/client/client.py
If 'bot_token' is explicitly defined, than that is used, otherwise if there is a bot token in the config.ini file that is used.
bot_token is set to None if not present
> Added support for bot_token inside config.ini file

- pyrogram/client/filters/filters.py
Enables easier and standard parsing, for quote wrapped args, etc.
Filters.command now has a posix argument, and the separator argument was
removed. shlex.split() works similar to having before separator=None.
> Improvements for message.command

- docs/source/topics/tgcrypto.rst
Recently Termux removed all -dev packages and merged them to the main packages.
```
$ apt install python-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
python
E: Package 'python-dev' has no installation candidate
```
So installing the `python` package now installs the header files also.
> Remove python-dev from docs for Termux

- pyrogram/session/session.py
added that when session.send coroutine is cancelled (or if any other exception is raised) the result should still be removed from the results list 
(#304 will be closed. merge this instead)
> fixed memory leak when session.send coroutine is cancelled

- pyrogram/client/types/user_and_chats/chat.py
Bound method of Chat export_invite_link() was referencing a non existing client attribute.
'Client' object has no attribute 'export_invite_link'
> Fixing Attribute Error on Chat.export_invite_link()

- pyrogram/client/methods/messages/send_poll.py
If correct_option_id == 0 then None is sent instead of 0
> Fix RPCError 400 QUIZ_CORRECT_ANSWER_EMPTY

- pyrogram/client/methods/chats/get_chat_members.py
- pyrogram/client/methods/chats/get_dialogs.py
- pyrogram/client/methods/messages/get_history.py
- pyrogram/client/methods/messages/get_messages.py
- pyrogram/client/methods/messages/send_media_group.py
I have added session names in "Sleeping for Xs" messages, as in plugins loaded info.
For example:
**[my_account] Sleeping for 5s**
> Session name in "Sleeping for Xs"

- pyrogram/client/methods/messages/send_poll.py
`await client.send_poll(...)` is actually returning a coroutine instead of the Message object
> Add missing await

- pyrogram/client/methods/messages/send_animation.py
- pyrogram/client/methods/messages/send_audio.py
- pyrogram/client/methods/messages/send_document.py
- pyrogram/client/methods/messages/send_video.py
Simple but useful changes for file-related send_* functions. Sometimes it need to send a file with specific filename, and not with its path basename. It's simpler and better to pass just a string instead of renaming original file.
> Add file_name param to file-related functions

- compiler/api/compiler.py
- docs/README.md
- pyrogram/client/client.py
- pyrogram/client/filters/filters.py
- pyrogram/client/methods/chats/delete_user_history.py
- pyrogram/client/methods/chats/get_chat_members.py
- pyrogram/client/methods/chats/get_dialogs.py
- pyrogram/client/methods/chats/set_chat_photo.py
- pyrogram/client/methods/chats/update_chat_username.py
- pyrogram/client/methods/messages/get_history.py
- pyrogram/client/methods/messages/get_messages.py
- pyrogram/client/methods/users/get_common_chats.py
- pyrogram/client/methods/users/update_profile.py
- pyrogram/client/methods/users/update_username.py
- pyrogram/client/types/inline_mode/chosen_inline_result.py
- pyrogram/client/types/messages_and_media/dice.py
- pyrogram/client/types/messages_and_media/message.py
- pyrogram/session/internals/msg_factory.py
- Use raw string in `compiler/api/compiler.py` re pattern.
- Trim trailing whitespaces from docstrings and code.
- Use `isinstance()` instead of `type()` for typechecking (isinstance is faster and the default way for typechecking).
- Cleaned up unused imports, mostly due to old code that was removed (Imports declared in docstrings were kept, though).
> Some fixes and speed improvments

- pyrogram/client/types/messages_and_media/message.py
Adds the functionality to access the message link.
Either as `t.me/c/` or `t.me/username` format.
> Add message.link attribute

- docs/source/intro/install.rst
v1 will drop support for python3.5, the docs also need to be updated
> Update python minimum version in v1 in docs

- pyrogram/client/methods/chats/get_nearby_chats.py
This fixes the `AttributeError: 'PeerUser' object has no attribute 'channel_id'`. Telegram must've changed the format.
Maybe we should also have a method to show nearby users?
> fix for new format

- pyrogram/client/methods/bots/answer_inline_query.py
Python 3.6 supports await inside comprehensions, and python 3.5 will be the EOL soon, then I rewrote a piece of it
> Update answer inline query to python3.6

- pyrogram/types/object.py
Title is self explanatory.
Added `__getstate__` to ignore `Object._client` while pickle is doing its job. ([What does __getstate__ do?](https://docs.python.org/3/library/pickle.html#object.__getstate__))
> Made pyrogram objects pickable

- pyrogram/methods/chats/get_chat.py
chatex.send now returns raw.types.Chat instead of types.Chat
> fix chat raw type

- docs/source/start/updates.rst
A spelling correction was made under the "Using add_handler()" section.
> Make spelling correction

- pyrogram/methods/chats/get_dialogs.py
Prevent
```
File "C:\Users\INT002327\AppData\Local\pypoetry\Cache\virtualenvs\josxabot-c3BmTbt9-py3.8\lib\site-packages\pyrogram\methods\chats\get_dialogs.py", line 92, in get_dialogs
to_id = message.to_id
└ pyrogram.raw.types.MessageEmpty(id=2767691)
AttributeError: 'MessageEmpty' object has no attribute 'to_id'
```
> Don't process MessageEmpty in get_dialogs

- compiler/docs/compiler.py
- pyrogram/methods/messages/__init__.py
- pyrogram/methods/messages/get_media_group.py
Method to get all media group messages knowing only one. Special thank to Danipulok (https://github.com/Danipulok) 
"Problems":
1) Docs
Doubt how to write correctly so I marked those lines with  "#TODO" + examples. 
2) Should it raises error in case it's passed "wrong" (not related to media group) message_id or just return an empty list? 
UPD(5.12.2020):
I just noticed that other media groups have media_group_id attribute too (playlists etc.)
So now I'm 100% sure this method supports all types of media groups(playlists, albums etc.)  as it should be :)
> New method - get_media_group() 

- pyrogram/methods/messages/inline_session.py
Fix for inline message id invalid when target dc is not dc4 or current dc
> Fix invalid inline message id

- pyrogram/methods/messages/search_global.py
I was recently getting this error on app.global_search() method:
```
File "/home/poki/.local/lib/python3.8/site-packages/pyrogram/methods/messages/search_global.py", line 71, in search_global
raw.functions.messages.SearchGlobal(
TypeError: __init__() missing 3 required keyword-only arguments: 'filter', 'min_date', and 'max_date'
```
Suprisingly no one has opened an issue for this except me.
Here is the context: https://t.me/pyrogramchat/281087
> this commit will fix issues with global_search()

- pyrogram/types/user_and_chats/chat.py
Added missing docstrings for `pyrogram.types.chat`: `iter_members()` and `get_members()`
> Missing-Docstrings

- pyrogram/methods/messages/copy_message.py
> typo in copy_message()

- pyrogram/types/messages_and_media/message.py
Added info regarding supergroup in forward_from_chat
> Missing info in forward_from_chat

- pyrogram/filters.py
Wrong documentation for filters.create, callable funcitions requires 3 positional arguments (filter, client, update) and not two.
> Fixed documentation

- pyrogram/types/bots_and_keyboards/game_high_score.py
Since `service.from_id` is None (chat with yourself), `utils.get_raw_peer_id` throws an error.
> Fix GameHighScore in the chat with yourself

- compiler/docs/compiler.py
- pyrogram/methods/messages/__init__.py
- pyrogram/methods/messages/copy_media_group.py
A new method client.copy_media_group. 
You pass a chat_id and a single ``message_id``, and ``media_group`` that contains message with this ``message_id`` will be copied.
It was useful for me so I thought I could PR this.
I wanted to create it as flexible as possible, so attribute ``captions`` became a little mess inside, but IMO it's gonna be easy in use in exchange.
Big thanks for Legenda24 for helping me [(github](https://github.com/Legenda24), [Telegram ](https://t.me/legendax24))
> Add method client.copy_media_group

- pyrogram/types/input_media/input_media.py
- pyrogram/types/input_media/input_media_animation.py
- pyrogram/types/input_media/input_media_audio.py
- pyrogram/types/input_media/input_media_document.py
- pyrogram/types/input_media/input_media_photo.py
- pyrogram/types/input_media/input_media_video.py
Changes:
1. all media parameter supports "URL",  so  updated docs for the same.
2. changed default value of caption from None to "", as can be seen below.
> added missing doc string for InputMedia types

- pyrogram/client.py
Currently, you can specify an uppercase parse_mode in Pyrogram methods, but not in Client instance:
```python
c = Client("my_client", parse_mode="HTML")
```
fails with:
```
ValueError: parse_mode must be one of "combined", "markdown", "md", "html" or None. Not "HTML"
```
However, in Client methods it works fine:
```python
c.send_message("me", "<b>Hi!</b>", parse_mode="HTML")
```
> Make parse_mode always lowercase

- pyrogram/types/bots_and_keyboards/callback_query.py
Since CallbackQuery.edit_message_text takes 4 arguments and CallbackQuery.edit_message_caption only 3, the reply_markup ends up to be the disable_web_page_preview one. Resolve this by specifying the argument name
> Fix to work with edit_message_caption works with reply_markup objects

- compiler/api/compiler.py
- compiler/api/template/combinator.txt
- pyrogram/raw/core/tl_object.py
- pyrogram/types/bots_and_keyboards/callback_query.py
Currently, the api compiler is using `data` as its function argument.  
However, [updateBotCallbackQuery](https://core.telegram.org/constructor/updateBotCallbackQuery) is use the same word `data` as its argument.  
It will cause the problem when the bot gets the callback query with no data (Like the game button).
Trying to fix issue #608 and make game button usable.
> Change variable name to avoid conflts with Telegram TL schema

- pyrogram/methods/chats/get_chat_members.py
This should solve the error `AttributeError: 'ChatParticipantsForbidden' object has no attribute 'participants'` and apply the commit https://github.com/pyrogram/pyrogram/commit/062a6ce6dd8e9cbc9ee18d6c7c43bae5607ed215 on this file, too.
> Fix: not always `r.full_chat.participants` has a `participants ` member.

- pyrogram/methods/messages/inline_session.py
Global session creates a problem for another bot. As that session was generated for another bot can't be used by this bot.
> Ability to run multiple bot with inline feature.

- pyrogram/filters.py
- tests/filters/test_command.py
When using `filters.command("start")`, the `/start` command returns `["start"]` as expected, but `/START` returns `["start", "START"]`, which may cause issues if relying on `m.command` to get arguments.
> Fix Message.command when case is different

- pyrogram/client.py
some times server don't send response if offset more then file size (i think some file storages don't support this behavior)
so fix in one line: need change condition for break loop to len(chunk) < limit
> fix for client.download_media consistently fails for photos for big channels -503 Timeout #664

- pyrogram/storage/memory_storage.py
- pyrogram/storage/storage.py
- pyrogram/utils.py
This is the old issue I was trying to open, but then I just found a way to duel with it.
<details>
<summary> Old Issue I was going to post </summary>
> Since Telegram had upgraded the `user_id` to `int64` data type,
I'was wondering how can we fix the problem when the user/bot's id is a `int64`?
>
> https://github.com/pyrogram/pyrogram/blob/bf9e1864141bdab1a4f20393c7d10fcf8c522f63/pyrogram/storage/storage.py#L73-L83
> The code below shows how `export_session_string` works
>
> https://github.com/pyrogram/pyrogram/blob/bf9e1864141bdab1a4f20393c7d10fcf8c522f63/pyrogram/storage/storage.py#L25
> This is the problem, `">B?256sI?"` is not competable for `int64`. The `I` is only for `unsigned int` as shown in official document in `Python`.
> If we need to fix it, we need to change it to …
> Fixing `export_session_string` the right way

- pyrogram/types/bots_and_keyboards/inline_keyboard_button.py
- pyrogram/types/bots_and_keyboards/login_url.py
According to the docs, bot username is optional
see - https://docs.pyrogram.org/api/types/LoginUrl#pyrogram.types.LoginUrl
> make bot username optional

- pyrogram/types/user_and_chats/chat.py
raising `AttributeError: 'NoneType' object has no attribute 'channel_id'` in case of channels and also if client is a bot.
> fix parsing send_as peer.

- compiler/api/compiler.py
- pyrogram/raw/core/future_salts.py
`compiler/api/compiler.py`
- Vector can cause empty `TLObject` sent when calling `write()`
`pyrogram/raw/core/future_salts.py`
- `ID` value missing in `write()`, can cause server to reject and force disconnect you.
This is tested by watsing 13 hours.
> 🐛 [Bug fixes] `compiler.py` and `future_salts.py`

- pyrogram/methods/messages/get_media_group.py
**Remove unnecessary method call in `get_media_group`**
Since currently `get_media_group` method is in stable version, also as `copy_media_groups`, which uses `get_media_group`, it's even more critical now. Currently, we use `get_messages` method twice, when only one call is needed.
[Old](https://github.com/pyrogram/pyrogram/pull/692) pull request from @Taijefx34 is closed because of conflicts, so this is a new one.
@delivrance, I really hope you could merge this as soon as possible and maybe even add it to hot fix version v1.3.2.
> Remove unnecessary method call in `get_media_group`

- pyrogram/parser/html.py
- The current spoiler implementaion unparses both strikethrough and spoiler tags with \<s\>, making them indistinguishable:
> Fix spoiler html unparsing

- pyrogram/parser/html.py
Simple reversed method didn't work with overlapping entities
> Now unparses overlapped entities

- pyrogram/file_id.py
in accordance with my tests (https://gist.github.com/andrew-ld/72f8ac8c41330a47c99a9f79958625eb), using a list and only at the end converting it in bytes is more efficient because bytes is an immutable instance.
```
testing sample 1
old 7.225026909000007
new 3.8671077140002126
testing sample 2
old 6.551758901000085
new 3.8057729349998226
testing sample 3
old 11.08116247199996
new 5.3508748690001084
testing sample 4
old 10.761553993000234
new 5.434736396000062
```
> faster pyrogram lre encode implementation

- docs/source/api/decorators.rst
The pyrogram.Client.on_chat_join_request() decorator was missing in the docs "decorators" section
> Add pyrogram.Client.on_chat_join_request() decorator to docs

- pyrogram/methods/bots/answer_inline_query.py
Mypy was complaining since List is considered invariant and I was trying to pass a list of `InlineQueryResultArticle` and it was expecting a list of `InlineQueryResult`.
```python
results = [
InlineQueryResultArticle(...),
]
await inline_query.answer(results=results, cache_time=1)
```
[mypy docs about this issue](https://mypy.readthedocs.io/en/stable/common_issues.html#invariance-vs-covariance)
I'm using `Iterable` instead of `Sequence` since it has more flexibility and allows generators etc.
> fix: inline query results typing

- pyrogram/methods/advanced/save_file.py
No need to use loop.create_task in workers, because we awaiting immediately
> Removed create_task

- pyrogram/types/messages_and_media/message.py
Missed during `Message.message_id` -> `Message.id` transition.
> Fix Message.react()

- pyrogram/methods/messages/send_photo.py
- pyrogram/methods/messages/send_video.py
- pyrogram/utils.py
Fixes `case 1` of issue [#829](https://github.com/pyrogram/pyrogram/issues/829)
> Fix for Self-Destruct if file_id and ttl_seconds are passed

- pyrogram/client.py
Pre-v2 code used to specify `api_id` explicitly, so allow storage to migrate non-interactively if `api_id` was already specified in `Client` constructor.
> Allow non-interactive migration from storage v2 to v3

- pyrogram/types/messages_and_media/message.py
`has_protected_content` attribute of Message class was assigned the wrong type in the docstring (str), corrected it to `bool`
> fix type of `has_protected_content`

- docs/source/faq/how-to-avoid-flood-waits.rst
*Link of incorrect:* [How to avoid Flood Waits?](https://docs.pyrogram.org/faq/how-to-avoid-flood-waits#how-to-avoid-flood-waits:~:text=the%20required%20seconds.-,import%20time,-from%20pyrogram.errors)
> Correct FAQ answer.

- pyrogram/methods/messages/edit_inline_media.py
- pyrogram/methods/messages/inline_session.py
Inline mode done right:
- Fixed `FilePartMissing: Telegram says: [400 FILE_PART_X_MISSING] - Part 0 of the file is missing from storage (caused by "messages.EditInlineBotMessage")` when editing a media in a chat which DC id is different by the bot's one
- `inline_session.get_session` always assumed to be in production server, changed it to `client.storage.test_mode()`
- `force_file=True` for `InputMediaDocument`
- `nosound_video=True` for `InputMediaAnimation`
- Implemented retries due to a server race condition which might lead to `MEDIA_EMPTY`
> Fix inline quirks and mistakes

- pyrogram/methods/auth/initialize.py
To avoid AttributeError we should store the "me" user object before starting dispatcher.
Error Logs:
```
06:34:23 PM - 229 - pyrogram.dispatcher - dispatcher - ERROR - 'NoneType' object has no attribute 'username'        
Traceback (most recent call last):
File "d:\Python Projects\Assistant\venv\lib\site-packages\pyrogram\dispatcher.py", line 226, in handler_worker
if await handler.check(self.client, parsed_update):
File "d:\Python Projects\Assistant\venv\lib\site-packages\pyrogram\handlers\handler.py", line 35, in check    
return await self.filters(client, update)
File "d:\Python Projects\Assistant\venv\lib\site-packages\pyrogram\filters.py", line 66, in __call__
x = await self.base(client, update)
File "d:\Python Projects\Assistant\venv\lib\site-packages\pyrogram\filters.py", line 760, …
```
> Store "me" user object before starting dispatcher

- pyrogram/parser/html.py
- pyrogram/utils.py
I guess it's fine to handle empty entities internally to avoid ENTITY_BOUNDS_INVALID , so the client won't send the empty entities
> Filter out empty entities internally

- pyrogram/methods/messages/edit_inline_media.py
⚠️ **Followup for https://github.com/pyrogram/pyrogram/pull/1036**
There was an issue with the previous Pull Request, which led to the method breaking with `InputMediaPhoto`.
- Usage with InputMediaPhoto
- Usage with BytesIO (anonymous BytesIO without a `.name` property is accepted as well)
- Use `uploadMedia` only for newly uploaded documents/photos (files or BytesIO)
- Refactoring
- Removed duplicated code
- Add BytesIO name in `DocumentAttributeFilename`, fallbacks to `"media"` if a `.name` property is not set
- Every InputMedia* with a local file
- Every InputMedia* with a external url
- Every InputMedia* with a named BytesIO media
- Every InputMedia* with an anonymous (without `.name`) BytesIO media
- Editing inline media in chats which DC is different by the bot's data center
I …
> Fixed and improved edit_inline_media once again

- pyrogram/methods/messages/get_custom_emoji_stickers.py
- pyrogram/types/messages_and_media/message.py
- pyrogram/types/messages_and_media/sticker.py
Video sticker resolution wasn't determined properly as it doesn't have DocumentAttributeImageSize attribute, but it does have DocumentAttributeVideo attribute. This PR fixes this.
Also DocumentAttributeVideo has duration property and it was added to Sticker type.
> Fix determining video sticker resolution. Add sticker duration to Sticker type

- pyrogram/methods/messages/get_custom_emoji_stickers.py
Although it says in the function's comment that an int can be passed directly, you should actually pass a list.
This PR is used to allow the function to be called when parameters of type Iterable and int are provided.
> Fix get_custom_emoji_stickers Int type

- pyrogram/client.py
Note: The asyncio.CancelledError() is re-raised to propagate to the caller
> Added tempfile deletion in case of asyncio task cancellation.

- pyrogram/parser/html.py
- pyrogram/parser/markdown.py
Added the field `language` when unparsing `PRE` entities (both markdown and html), which was being completely ignored.
Not added when parsing (yet)
> added `language` to entities when unparsing

- pyrogram/methods/decorators/on_disconnect.py
- pyrogram/methods/decorators/on_raw_update.py
Believe or not, this is the only handler that's not working
```py3
@Client.on_disconnect()
async def disconnect(client: Client):
pass
````
> Fix on_disconnect decorator not working

- pyrogram/methods/messages/copy_message.py
Method returns Message type, but type-hint say's that method will return List of Message
> Returns:
:obj:`~pyrogram.types.Message`: On success, the copied message is returned.
> > DOCSTRING
> Type-Hint Fix

- pyrogram/parser/html.py
Using a deque to preserve the order of open and closed tags when unparsing overlapping entities
> Unparsing html entities with deque
