pyrogram/pyrogram

compiler/error/source/400_BAD_REQUEST.tsv

hi!
```
pyrogram.api.errors.error.UnknownError: [520 Unknown error]: {
"_": "types.RpcError",
"error_code": 400,
"error_message": "USERNAME_OCCUPIED"
}
```

Error [400 USERNAME_OCCUPIED]

---

pyrogram/client/client.py
pyrogram/client/dispatcher/dispatcher.py

remove_handler and locks

---

pyrogram/client/client.py

use new session when uploading files instead of main session

fixed session mistake

---

pyrogram/__init__.py
pyrogram/client/__init__.py
pyrogram/client/dispatcher/dispatcher.py
pyrogram/client/ext/utils.py
pyrogram/client/filters/filters.py
pyrogram/client/handlers/__init__.py
pyrogram/client/handlers/deleted_messages_handler.py
pyrogram/client/methods/decorators/__init__.py
pyrogram/client/methods/decorators/on_deleted_messages.py
pyrogram/client/types/update.py

Added a handler for deleted messages according to the open enhancement #88

Add deleted messages handler

---

docs/source/index.rst
docs/source/resources/UpdateHandling.rst
docs/source/start/Installation.rst
docs/source/start/Setup.rst
docs/source/start/Usage.rst
pyrogram/client/filters/filters.py

Allow multiple command prefixes in a single filter

---

docs/source/pyrogram/Client.rst
pyrogram/client/methods/users/__init__.py
pyrogram/client/methods/users/delete_user_profile_photos.py
pyrogram/client/methods/users/set_profile_photo.py
pyrogram/client/methods/users/set_user_profile_photo.py

Add set_profile_photo method

---

docs/source/index.rst
docs/source/resources/Plugins.rst
pyrogram/client/client.py
pyrogram/client/ext/base_client.py
pyrogram/client/methods/decorators/on_callback_query.py
pyrogram/client/methods/decorators/on_deleted_messages.py
pyrogram/client/methods/decorators/on_disconnect.py
pyrogram/client/methods/decorators/on_message.py
pyrogram/client/methods/decorators/on_raw_update.py

Add plugin system

---

pyrogram/client/filters/filters.py

added Filters.chat("me")

---

pyrogram/client/filters/filters.py

added Filters.user("me")

---

pyrogram/client/types/messages_and_media/message.py

added args to Message.download bound method

---

pyrogram/client/dispatcher/dispatcher.py

Hello! 
I have been using RavUpdateNandler for a long time, but after the update it began to behave strangely. As I understood from the code, after processing the raw update from the telegrams, the variable with the raw update is overwritten and there is no longer a "raw" update.
Hotfix working for me.

fix RawUpdateHandler

---

docs/source/resources/SmartPlugins.rst
pyrogram/client/client.py

Smart plugins enhancements

---

pyrogram/client/methods/messages/edit_message_media.py

For some reason, message editing has completely missed thumbnails.

Fixed loss of thumbnails after media editing.

---

pyrogram/client/client.py

Fix plugins on Windows (closes #217)

Fix plugins import on windows

---

pyrogram/client/methods/messages/send_document.py
pyrogram/client/methods/messages/send_poll.py
pyrogram/client/types/messages_and_media/message.py

message.reply_animation
message.reply_audio
message.reply_cached_media
message.reply_chat_action
message.reply_contact
message.reply_document
message.reply_game
message.reply_inline_bot_result
message.reply_location
message.reply_media_group
message.reply_photo
message.reply_poll
message.reply_sticker
message.reply_venue
message.reply_video
message.reply_video_note
message.reply_voice
message.edit_caption
message.edit_media
message.edit_reply_markup
message.pin
fixed send_document docstrings while doing so
uniformed function declaration of send_poll

Added convenience methods

---

pyrogram/client/methods/messages/forward_messages.py
pyrogram/client/methods/messages/send_contact.py
pyrogram/client/style/html.py
pyrogram/client/style/markdown.py
pyrogram/client/types/messages_and_media/message.py
pyrogram/client/types/messages_and_media/messages.py
pyrogram/client/types/pyrogram_type.py

Add ability to forward messages as copies

---

pyrogram/client/filters/filters.py

Make Filtering for specific callback_query's easier.

Add Filter for Callback_Query.data

---

pyrogram/client/types/messages_and_media/message_entity.py

[As I've mentioned in the Lounge already](https://t.me/PyrogramLounge/74814), here's your PR

Put italic in quotes, adapt text_mention

---

pyrogram/client/methods/contacts/add_contacts.py
pyrogram/client/methods/users/block_user.py
pyrogram/client/methods/users/unblock_user.py

Also added a returned object for the docs, so it's not blank there. [As discussed in the Pyrogram Lounge](https://t.me/PyrogramLounge/75818).

 Add convenience methods to block and unblock Users

---

.gitignore
docs/source/index.rst
docs/source/topics/scheduling.rst

This pull request adds usage examples of pyrogram with different scheduling libraries(schedule and apscheduler)

Add section to docs about scheduling

---

pyrogram/client/parser/html.py
pyrogram/client/parser/markdown.py

Add better support for nested entities (both for HTML and Markdown)

---

pyrogram/client/types/user_and_chats/chat.py

Title says it all.
RE: https://t.me/PyrogramChat/108088

Add export_invite_link bound method

---

pyrogram/client/methods/users/__init__.py
pyrogram/client/methods/users/get_common_chats.py

```python
for chat in app.get_common_chats('haskell'):
print(chat)
```

Add get_common_chats method

---

pyrogram/client/types/user_and_chats/user.py

Meanwhile I've taken the liberty and removed whitespaces from empty lines.

Add bound method for get_common_chats()

---

pyrogram/client/client.py
pyrogram/client/ext/file_data.py
pyrogram/client/methods/messages/download_media.py
pyrogram/client/types/user_and_chats/chat_photo.py

Fix non-user chat photos failing to download

---

pyrogram/client/methods/messages/edit_message_media.py

1. fix missing await
2. fix empty file reference

[asyncio] 

---

pyrogram/client/methods/messages/stop_poll.py

Otherwise stop_poll() raises AtributeError thile trying to convert a string to bytes

Poll ID should be INT

---

pyrogram/client/methods/chats/set_chat_photo.py

add missing file_ref in set_chat_photo

---

pyrogram/client/methods/chats/set_chat_photo.py

Revert "add missing file_ref in set_chat_photo"

---

compiler/docs/compiler.py
pyrogram/client/types/user_and_chats/chat.py

Bound methods for get_chat_member, get_chat_members, iter_chat_members, add_chat_members

Add more bound methods

---

pyrogram/client/filters/filters.py

maybe filter's name is not the best but that's the only thing I could think of

filter messages coming from the channel connected to the chat

---

pyrogram/client/client.py

`set_parse_mode` should be deprecated in the next major version.

Add parse_mode property to Client

---

pyrogram/client/types/messages_and_media/message.py

reply_* bound methods weren't added to handle BinaryIO object, now they are.

Update reply_* bound methods to support BinaryIO

---

pyrogram/client/client.py

Loading plugins shouldn't be considered a warning

Change logging hierarchy for loading plugins

---

pyrogram/methods/messages/download_media.py

Made Message.new_chat_photo downloadable

---

pyrogram/types/user_and_chats/chat.py

Update chat.py (members_count)

---

README.md
docs/source/conf.py
pyrogram/__init__.py

Dan is very outdated

---

pyrogram/parser/html.py

Thanks for this great library , enough documentations to start-with and even beginner friendly ;)

Fix for strikethrough entity unparsing

---

pyrogram/types/input_media/input_media_audio.py

Fix Typo in input_media_audio()

---

pyrogram/types/messages_and_media/message.py

Ok, here it is. Special thank to Danipulok (https://github.com/Danipulok)

Bound method - get_media_group()

---

pyrogram/types/object.py

This commit will prevert other user obtain real phone number length.

Use fixed length instead of dynamic length to mask phone number

---

pyrogram/client.py
pyrogram/methods/decorators/on_callback_query.py
pyrogram/methods/decorators/on_chosen_inline_result.py
pyrogram/methods/decorators/on_deleted_messages.py
pyrogram/methods/decorators/on_inline_query.py
pyrogram/methods/decorators/on_message.py
pyrogram/methods/decorators/on_poll.py
pyrogram/methods/decorators/on_raw_update.py
pyrogram/methods/decorators/on_user_status.py

combination of decorators with plugins has solved

---

pyrogram/types/inline_mode/__init__.py
pyrogram/types/inline_mode/inline_query_result_audio.py

Added audio support for inline query
credits: DogeSaveTheGod

add-inline-query-audio

---

pyrogram/methods/chats/__init__.py
pyrogram/methods/chats/get_chat_onlines.py

Used to get the number of online users in a specific group.

Add get_chat_onlines method

---

pyrogram/sync.py

Hi, Thanks for this awesome project. I have been using **Pyrogram** for a long time.
But recently got some issues with Threads + Event loops.
Here how i reproduced them.
https://gist.github.com/rking32/818bd60a6dd1e632ac61ba6f7e902a5a
Finally was able to fix them.

improved async to sync wrapper

---

pyrogram/raw/core/primitives/vector.py

This fixes #678 and, more in general, any method returning a vector containing bare longs.

Fix reading vectors of bare longs

---

pyrogram/methods/chats/delete_user_history.py

`raw.functions.channels.DeleteUserHistory` to `raw.functions.channels.DeleteParticipantHistory`

Fix delete_user_history()

---

pyrogram/methods/messages/send_chat_action.py

Layer 123 introduced to History Import -> https://github.com/pyrogram/pyrogram/commit/c3819ddb56cccb6c28155032a61c3d1b58403675
Layer 132 introduced to Sticker Choose -> https://github.com/pyrogram/pyrogram/commit/320696b4b23c688d0488a6dbd2b1c9ca32ba4517

Add new chat action

---

compiler/errors/source/400_BAD_REQUEST.tsv

Add the RPC error about some chats restrict forwarding
Fixes #820

Add RPC Error: CHAT_FORWARDS_RESTRICTED

---

compiler/docs/compiler.py
pyrogram/methods/chats/__init__.py
pyrogram/methods/chats/toggle_no_forwards.py
pyrogram/types/user_and_chats/chat.py

Hi, I'm not sure if the code is completely correct, but I tested both enabling and disabling on a private channel and it worked.
If you have any point of improvement, feel free to send me or change it.

Add No Forwards chat option

---

pyrogram/parser/parser.py

Bug with sending None in caption in send_* methods

---

pyrogram/methods/messages/send_animation.py
pyrogram/methods/messages/send_audio.py
pyrogram/methods/messages/send_document.py
pyrogram/methods/messages/send_video.py

Respect `file_name` if file passed is a file object

---

pyrogram/types/messages_and_media/message.py

Added missing Attributes for `message.reply_text`

---

pyrogram/methods/bots/set_bot_commands.py
pyrogram/types/bots_and_keyboards/__init__.py
pyrogram/types/bots_and_keyboards/bot_command.py

Small changes to fix the issue, I have set arguments with default value.
close #777

Fix issue in set_bot_commands

---

pyrogram/client.py

download media on windows fix

---

pyrogram/methods/contacts/delete_contacts.py
pyrogram/methods/messages/delete_messages.py
pyrogram/methods/messages/forward_messages.py
pyrogram/methods/messages/get_messages.py
pyrogram/methods/users/get_common_chats.py
pyrogram/methods/users/get_users.py

It's untested code
Appropriate description should be there in commit messages

methods: Drop support for iterators where they are not needed

---

compiler/errors/source/400_BAD_REQUEST.tsv

added STICKERS_TOO_MUCH, STICKERSET_NOT_MODIFIED, STICKER_VIDEO_NOWEBM error description

added STICKERS_TOO_MUCH, STICKERSET_NOT_MODIFIED, STICKER_VIDEO_NOWEBM

---

pyrogram/types/messages_and_media/message.py

Added missing field: forwards

---

pyrogram/filters.py

This pull request fixes #1136.
Signed-off-by: Aliwoto <woto@kaizoku.cyou>

Use getattr to get outgoing attribute from the message in me_filter.

---

pyrogram/client.py

Handle all given updates, avoid short circuit

---

pyrogram/client.py
pyrogram/enums/next_code_type.py
pyrogram/enums/sent_code_type.py

Fix FRAGMENT_SMS

---

compiler/errors/source/400_BAD_REQUEST.tsv

Error when premium user banned video messages

add VOICE_MESSAGES_FORBIDDEN
